"""
Abstract base class for all LLM agents for the experiment.

Every agent - local (MLX) or cloud (OpenAI, Anthropic) must satisfy this interface
so that runner.py can swap providers with zero changes.

Contract
----------
    agent.model_id                  -> str
    agent.query(prompt, variant)    -> AgentResponse
    agent.unload()                  -> None (no-op for API agents)

AgentResponse is defined as cannonical shared dataclass.
mlx_agent.py defines its own copy for historical reasons; that local copy
is compatible (field for field) with this one.
"""

from __future__ import annotations
import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)


# shared response type
@dataclass
class AgentResponse:
    """
    Structured response returned by every agent

    Fields
    ----------
    text: raw text generated by the model
    prompt_tokens: number of tokens in the input prompt (exact or estimated)
    completion_tokens: number of tokens in the generated output
    latency_ms: time from request to first complete response (ms)
    model_id: model identifier str
    variant: prompt variant label set by the caller
    metadata: optional dict for provider-specific extras
    """
    text: str
    prompt_tokens: int
    completion_tokens: int
    latency_ms: float
    model_id: str
    variant: str = "unknown"
    metadata: dict = field(default_factory=dict)


# abstract base agent
class BaseAgent(ABC):
    """
    Abstract LLM agent

    Subclasses must implement query(). The unload method is a no-op by
    default because API agents don't hold in-process model weights;
    only MLXAgent overrides it to free unified memory.
    """
    @property
    @abstractmethod
    def model_id(self) -> str:
        """Canonical model id string, ex: gpt-4o-mini"""
    
    @abstractmethod
    def query(self, prompt: str, variant: str = "unknown") -> AgentResponse:
        """
        Send a single prompt to the model and return a structured response.

        Args:
            prompt: the full formatted prompt str, already built by PromptBuilder.
                    The agent must not modify it.
            variant: label for the experiment variant. Stored in the
                     returned AgentResponse for downstream analysis
        
        Returns:
            AgentResponse
        """
    
    def unload(self) -> None:
        """
        Release any resources held by this agent.

        API-based agents are stateless between calls, so the default
        implementation is a no-op. MLXAgent overrides this to drop
        weights from unified memory.
        """
        logger.debug("%s.unload() called (no-op for API agents.)", self.__class__.__name__)
